import { useMemo, useState } from 'react';
import { DATA_COLORS } from '../../core/colors.ts';
import { Latex } from '../../core/Latex.tsx';
import { ChartSvg } from '../../core/svg/ChartSvg.tsx';
import svgStyles from '../../core/svg/svg.module.css';
import { useParameters } from '../../core/useParameters.ts';
import { usePlayback } from '../../core/usePlayback.ts';
import { useResettableState } from '../../core/useSeededRandom.ts';
import { VizFrame } from '../../core/VizFrame.tsx';
import styles from './SetStructures.module.css';

const SUBSETS_PER_SECOND = 1.5;

function popCount(value: number): number {
  let count = 0;
  for (let v = value; v > 0; v >>= 1) count += v & 1;
  return count;
}

interface PowerSetViewProps {
  title: string;
  elements: readonly string[];
}

/**
 * Subsets generated by counting in binary: bit i says whether element i is
 * included. They are arranged by size, the levels of the inclusion lattice,
 * and edges join subsets that differ in one element.
 */
export function PowerSetView({ title, elements }: PowerSetViewProps) {
  const definitions = useMemo(
    () => [
      {
        type: 'number' as const,
        key: 'n',
        label: 'Número de elementos',
        symbol: 'n',
        min: 1,
        max: elements.length,
        step: 1,
        default: Math.min(3, elements.length),
      },
    ],
    [elements.length],
  );
  const parameters = useParameters(definitions);
  const n = Number((parameters.values as Record<string, number>).n);
  const items = elements.slice(0, n);
  const total = 2 ** n;
  const [run, setRun] = useState(0);
  const [generated, update] = useResettableState<number>(`${n}|${run}`, () => 0);
  const playback = usePlayback({
    step: () => update((value) => Math.min(total, value + 1)),
    reset: () => setRun((value) => value + 1),
    rate: SUBSETS_PER_SECOND,
    done: generated >= total,
  });
  const label = (mask: number) => {
    const chosen = items.filter((_, index) => (mask >> index) & 1);
    return chosen.length === 0 ? '∅' : `{${chosen.join(', ')}}`;
  };
  const code = (mask: number) =>
    Array.from({ length: n }, (_, index) => ((mask >> (n - 1 - index)) & 1 ? '1' : '0')).join('');
  const current = generated - 1;
  const description =
    `El conjunto {${items.join(', ')}} tiene ${n} elementos y 2 a la ${n} igual a ${total} subconjuntos. ` +
    (current >= 0 ? `Subconjunto ${generated}: código ${code(current)}, ${label(current)}.` : '');

  return (
    <VizFrame
      title={title}
      playback={playback}
      parameters={{ ...parameters, values: parameters.values as Record<string, unknown> }}
      readouts={[
        { label: 'Elementos n', value: String(n) },
        { label: 'Subconjuntos generados', value: `${generated} de ${total}` },
        ...(current >= 0
          ? [{ label: 'Código binario actual', value: code(current), color: DATA_COLORS.highlight }]
          : []),
        { label: '|P(S)| = 2ⁿ', value: String(total) },
      ]}
      description={description}
    >
      <p className={styles.notation}>
        <Latex
          tex={`\\mathcal{P}(\\{${items.join(', ')}\\}),\\quad |\\mathcal{P}(S)| = 2^{${n}} = ${total}`}
        />
      </p>
      <ChartSvg
        label={description}
        aspect={0.6}
        minHeight={260}
        maxHeight={460}
        margins={{ top: 20, right: 12, bottom: 20, left: 12 }}
      >
        {(box) => {
          const levels = Array.from({ length: n + 1 }, (_, size) =>
            Array.from({ length: total }, (_, mask) => mask).filter(
              (mask) => popCount(mask) === size,
            ),
          );
          const position = new Map<number, { x: number; y: number }>();
          levels.forEach((level, size) => {
            level.forEach((mask, index) => {
              position.set(mask, {
                x: box.inner.left + (box.inner.width * (index + 0.5)) / level.length,
                y: box.inner.top + box.inner.height - (box.inner.height * size) / Math.max(1, n),
              });
            });
          });
          const nodeWidth = Math.min(
            96,
            (box.inner.width / Math.max(...levels.map((level) => level.length))) * 0.9,
          );
          return (
            <>
              {Array.from({ length: total }, (_, mask) =>
                items.map((_, bit) => {
                  if ((mask >> bit) & 1) return null;
                  const upper = mask | (1 << bit);
                  const from = position.get(mask);
                  const to = position.get(upper);
                  if (!from || !to) return null;
                  const visible = mask < generated && upper < generated;
                  return (
                    <line
                      key={`${mask}-${upper}`}
                      x1={from.x}
                      y1={from.y}
                      x2={to.x}
                      y2={to.y}
                      stroke="var(--color-border-strong)"
                      strokeOpacity={visible ? 0.8 : 0.15}
                      aria-hidden="true"
                    />
                  );
                }),
              )}
              {Array.from({ length: total }, (_, mask) => {
                const point = position.get(mask);
                if (!point) return null;
                const visible = mask < generated;
                return (
                  <g key={mask} aria-hidden="true" opacity={visible ? 1 : 0.2}>
                    <rect
                      x={point.x - nodeWidth / 2}
                      y={point.y - 16}
                      width={nodeWidth}
                      height={32}
                      rx={8}
                      fill={mask === current ? DATA_COLORS.highlight : 'var(--color-surface)'}
                      fillOpacity={mask === current ? 0.35 : 1}
                      stroke={DATA_COLORS.primary}
                    />
                    <text
                      x={point.x}
                      y={point.y - 3}
                      textAnchor="middle"
                      className={svgStyles.label}
                      style={{ fontSize: 11 }}
                    >
                      {label(mask)}
                    </text>
                    <text
                      x={point.x}
                      y={point.y + 11}
                      textAnchor="middle"
                      className={svgStyles.labelMuted}
                      style={{ fontSize: 9, fontFamily: 'var(--font-mono)' }}
                    >
                      {code(mask)}
                    </text>
                  </g>
                );
              })}
            </>
          );
        }}
      </ChartSvg>
    </VizFrame>
  );
}
