import { useMemo, useState } from 'react';
import { bell, bellTriangle, setPartitions, stirling2 } from '../../../lib/combinatorics/index.ts';
import { DATA_COLORS } from '../../core/colors.ts';
import { Latex } from '../../core/Latex.tsx';
import { useParameters } from '../../core/useParameters.ts';
import { usePlayback } from '../../core/usePlayback.ts';
import { useResettableState } from '../../core/useSeededRandom.ts';
import { VizFrame } from '../../core/VizFrame.tsx';
import { PartitionChip } from './PartitionChip.tsx';
import { PartitionDiagram } from './PartitionDiagram.tsx';
import styles from './SetPartitionsViz.module.css';

const MIN_PER_SECOND = 1;
const TARGET_SECONDS = 25;

interface BellViewProps {
  title: string;
  n: number;
}

/**
 * Every partition of {1, ..., n}, generated by placing the elements in order:
 * each one joins an existing block or opens a new one. The total is the Bell
 * number, the sum over k of the Stirling numbers S(n, k).
 */
export function BellView({ title, n }: BellViewProps) {
  const definitions = useMemo(
    () => [
      {
        type: 'number' as const,
        key: 'n',
        label: 'Elementos',
        symbol: 'n',
        min: 1,
        max: 6,
        step: 1,
        default: n,
      },
    ],
    [n],
  );
  const parameters = useParameters(definitions);
  const size = Number((parameters.values as Record<string, number>).n);
  const all = useMemo(() => setPartitions(size), [size]);
  const total = all.length;
  const [run, setRun] = useState(0);
  const [shown, update] = useResettableState<number>(`${size}|${run}`, () => 0);
  const playback = usePlayback({
    step: () => update((value) => Math.min(total, value + 1)),
    reset: () => setRun((value) => value + 1),
    rate: Math.max(MIN_PER_SECOND, total / TARGET_SECONDS),
    done: shown >= total,
  });
  const current = shown > 0 ? all[shown - 1] : undefined;
  const byBlocks = Array.from(
    { length: size + 1 },
    (_, k) => all.slice(0, shown).filter((partition) => partition.length === k).length,
  );
  const triangle = bellTriangle(Math.max(size + 1, 2));
  const written = (blocks: readonly (readonly number[])[]) =>
    blocks.map((block) => `{${block.map((element) => element + 1).join(', ')}}`).join(' ');
  const description =
    `El conjunto {1, ..., ${size}} tiene B(${size}) = ${bell(size)} particiones. Listadas: ${shown}.` +
    (current ? ` La actual es ${written(current)}.` : '');

  return (
    <VizFrame
      title={title}
      playback={playback}
      parameters={{ ...parameters, values: parameters.values as Record<string, unknown> }}
      readouts={[
        { label: `B(${size})`, value: String(bell(size)), color: DATA_COLORS.primary },
        { label: 'Listadas', value: `${shown} de ${total}` },
        ...Array.from({ length: size }, (_, index) => ({
          label: `Con ${index + 1} bloque${index === 0 ? '' : 's'}`,
          value: `${byBlocks[index + 1] ?? 0} de ${stirling2(size, index + 1)}`,
        })),
      ]}
      description={description}
      dataTable={{
        caption: 'Triángulo de Bell: la primera entrada de cada fila es B(n)',
        columns: ['n', 'fila'],
        rows: triangle.map((row, index) => [index, row.join('  ')]),
      }}
    >
      <p className={styles.formula}>
        <Latex
          tex={`B_{${size}} = \\sum_{k=1}^{${size}} S(${size}, k) = ${Array.from({ length: size }, (_, index) => stirling2(size, index + 1)).join(' + ')} = ${bell(size)}`}
        />
      </p>
      <PartitionDiagram n={size} blocks={current ?? []} label={description} />
      <ul tabIndex={0} className={styles.list} aria-label="Particiones listadas">
        {all.slice(0, shown).map((partition, index) => (
          <PartitionChip key={index} blocks={partition} current={index === shown - 1} />
        ))}
      </ul>
    </VizFrame>
  );
}
