import type { CatalogExample } from '../examples.ts';

/** Catalog entries for the descriptive statistics visualizations. */
export const DESCRIPTIVE_EXAMPLES: CatalogExample[] = [
  {
    component: 'DataTypesViz',
    title: 'Población y muestra',
    params: {
      modo: 'poblacion',
      enfoque: 'muestra',
      tamano: 200,
      n: 12,
      forma: 'normal',
      centro: 165,
      dispersion: 8,
      estadistico: 'media',
      unidad: 'estudiante',
      variable: 'Estatura (cm)',
    },
  },
  {
    component: 'DataTypesViz',
    title: 'Parámetro y estadístico',
    params: {
      modo: 'poblacion',
      enfoque: 'parametro',
      tamano: 300,
      n: 20,
      forma: 'bernoulli',
      centro: 0.35,
      estadistico: 'proporcion',
      unidad: 'votante',
      variable: 'Apoya la propuesta',
      exito: 'sí',
    },
  },
  {
    component: 'DataTypesViz',
    title: 'Clasificar por escala',
    params: {
      modo: 'clasificar',
      eje: 'escala',
      ejemplos: [
        {
          nombre: 'Tipo de sangre',
          valores: 'A, B, AB, O',
          clase: 'nominal',
          razon: 'Solo distingue grupos.',
        },
        {
          nombre: 'Talla',
          valores: 'CH, M, G',
          clase: 'ordinal',
          razon: 'Hay orden, pero no distancias.',
        },
        {
          nombre: 'Año',
          valores: '1990, 2024',
          clase: 'intervalo',
          razon: 'El año cero es convencional.',
        },
        {
          nombre: 'Ingreso',
          valores: '0, 8500',
          clase: 'razon',
          razon: 'El cero es ausencia de ingreso.',
        },
      ],
    },
  },
  {
    component: 'DataTypesViz',
    title: 'Discreto y continuo',
    params: {
      modo: 'valores',
      discreta: { nombre: 'Hijos por hogar', unidad: 'hijos', desde: 2 },
      continua: { nombre: 'Estatura', unidad: 'cm', desde: 160, valor: 172.3648 },
    },
  },
  {
    component: 'DataTypesViz',
    title: 'Escalas',
    params: { modo: 'escalas', variable: 'temperatura' },
  },
  {
    component: 'DataTypesViz',
    title: 'Panel',
    params: {
      modo: 'panel',
      unidades: ['Jalisco', 'Sonora', 'Yucatán', 'Puebla'],
      periodos: ['2020', '2021', '2022', '2023'],
      variable: 'Desempleo (%)',
      valores: [
        [4.9, 4.1, 3.2, 2.9],
        [4.4, 3.8, 3.1, 2.8],
        [3.1, 2.6, 2.2, 2.0],
        [3.8, 3.5, 2.9, 2.6],
      ],
      faltantes: [[2, 1]],
    },
  },
  {
    component: 'DataTypesViz',
    title: 'Estructura',
    params: { modo: 'estructura', caso: 'pedidos' },
  },
  {
    component: 'DataTypesViz',
    title: 'Datos ordenados',
    params: { modo: 'ordenados', caso: 'clima' },
  },
  {
    component: 'DataStrip',
    title: 'Medidas de centro con atípico',
    params: {
      modo: 'centro',
      datos: [12, 15, 14, 18, 15, 13, 16],
      medidas: ['media', 'mediana', 'moda'],
      atipico: { indice: 6, hasta: 45 },
      variable: 'Minutos de traslado',
      unidad: 'min',
      decimales: 0,
    },
  },
  {
    component: 'DataStrip',
    title: 'Balanza y media ponderada',
    params: {
      modo: 'centro',
      datos: [7.5, 8.8, 9.4, 6.9],
      pesos: [8, 6, 4, 2],
      medidas: ['ponderada', 'media'],
      balanza: true,
      variable: 'Calificación',
      etiquetas: ['Cálculo', 'Física', 'Química', 'Taller'],
    },
  },
  {
    component: 'DataStrip',
    title: 'Recortada y winsorizada',
    params: {
      modo: 'centro',
      datos: [3.1, 3.4, 3.3, 3.6, 3.2, 3.5, 3.3, 3.4, 9.8, 0.4],
      medidas: ['recortada', 'winsorizada', 'media'],
      proporcion: 0.1,
      variable: 'Peso al nacer',
      unidad: 'kg',
    },
  },
  {
    component: 'DataStrip',
    title: 'Semicírculo de medias',
    params: { modo: 'semicirculo', a: 4, b: 9 },
  },
  {
    component: 'DataStrip',
    title: 'Varianza con cuadrados',
    params: {
      modo: 'dispersion',
      datos: [4, 7, 5, 9, 10],
      medida: 'varianza',
      lecturas: ['varianza', 'desviacion', 'rango'],
      cuadrados: true,
      variable: 'Horas de estudio',
      decimales: 0,
    },
  },
  {
    component: 'DataStrip',
    title: 'Coeficiente de variación comparado',
    params: {
      modo: 'dispersion',
      datos: [62, 70, 75, 68, 80],
      medida: 'cv',
      lecturas: ['desviacion', 'cv'],
      banda: true,
      variable: 'Peso de adultos',
      unidad: 'kg',
      decimales: 0,
      comparar: { datos: [3.1, 3.4, 2.8, 3.6, 3.3], variable: 'Peso al nacer', unidad: 'kg' },
    },
  },
  {
    component: 'DataStrip',
    title: 'Corrección de Bessel',
    params: { modo: 'bessel', n: 4, media: 50, desviacion: 10, variable: 'calificaciones' },
  },
  {
    component: 'DataStrip',
    title: 'Cuartiles',
    params: {
      modo: 'cuantiles',
      datos: [12, 15, 17, 18, 21, 22, 25, 28, 31, 40],
      familia: 'cuartiles',
      variable: 'Minutos',
      decimales: 0,
    },
  },
  {
    component: 'DataStrip',
    title: 'Métodos de cuantiles',
    params: {
      modo: 'cuantiles',
      datos: [3, 6, 7, 8, 8, 10, 13, 15],
      familia: 'cuantil',
      p: 0.25,
      compararMetodos: true,
      variable: 'Valor',
      decimales: 0,
    },
  },
  {
    component: 'DataStrip',
    title: 'Diagrama de caja paso a paso',
    params: {
      modo: 'caja',
      datos: [52, 55, 58, 60, 61, 63, 64, 66, 70, 95],
      variable: 'Pulsaciones',
      unidad: 'lpm',
      decimales: 0,
    },
  },
  {
    component: 'DataStrip',
    title: 'Puntuaciones z de dos exámenes',
    params: {
      modo: 'estandarizar',
      grupos: [
        { datos: [62, 70, 75, 81, 85, 68, 73], variable: 'Matemáticas', resaltar: 4 },
        { datos: [55, 60, 58, 72, 65, 63, 61], variable: 'Física', resaltar: 3 },
      ],
      decimales: 0,
    },
  },
  {
    component: 'DataStrip',
    title: 'Asimetría',
    params: {
      modo: 'forma',
      enfoque: 'asimetria',
      forma: 'sesgo-derecha',
      formas: ['sesgo-derecha', 'sesgo-izquierda'],
      parametro: 2,
      centro: 30,
      escala: 8,
      variable: 'Tiempo de espera',
      unidad: 'min',
    },
  },
  {
    component: 'DataStrip',
    title: 'Modas',
    params: {
      modo: 'forma',
      enfoque: 'modas',
      forma: 'mezcla',
      parametro: 4,
      centro: 170,
      escala: 6,
      variable: 'Estatura',
      unidad: 'cm',
    },
  },
  {
    component: 'DataStrip',
    title: 'Colas',
    params: {
      modo: 'forma',
      enfoque: 'colas',
      forma: 'colas-pesadas',
      parametro: 3,
      n: 1000,
      centro: 0,
      escala: 1,
      variable: 'Rendimiento diario',
      unidad: '%',
    },
  },
  {
    component: 'AssociationViz',
    title: 'Covarianza con rectángulos',
    params: {
      modo: 'correlacion',
      medida: 'covarianza',
      lecturas: ['covarianza', 'pearson'],
      puntos: [
        [2, 3],
        [4, 4],
        [5, 7],
        [7, 6],
        [9, 10],
      ],
      nombres: { x: 'Horas de estudio', y: 'Calificación' },
      decimales: 0,
    },
  },
  {
    component: 'AssociationViz',
    title: 'Spearman con rangos',
    params: {
      modo: 'correlacion',
      medida: 'spearman',
      lecturas: ['pearson', 'spearman'],
      generador: { tipo: 'exponencial', n: 12, ruido: 0.1 },
      nombres: { x: 'Dosis', y: 'Respuesta' },
    },
  },
  {
    component: 'AssociationViz',
    title: 'Kendall por pares',
    params: {
      modo: 'correlacion',
      medida: 'kendall',
      lecturas: ['kendall', 'spearman'],
      puntos: [
        [1, 2],
        [2, 1],
        [3, 4],
        [4, 3],
        [5, 5],
      ],
      nombres: { x: 'Juez A', y: 'Juez B' },
      decimales: 0,
    },
  },
  {
    component: 'AssociationViz',
    title: 'Correlación de distancia',
    params: {
      modo: 'correlacion',
      medida: 'distancia',
      lecturas: ['distancia', 'pearson'],
      generador: { tipo: 'parabola', n: 30, ruido: 0.2 },
      nombres: { x: 'Temperatura', y: 'Consumo de energía' },
    },
  },
  {
    component: 'AssociationViz',
    title: 'Confusor',
    params: {
      modo: 'confusor',
      vista: 'grupos',
      nombres: { x: 'Helados vendidos', y: 'Golpes de calor', z: 'Mes' },
      niveles: ['Enero', 'Abril', 'Julio'],
      n: 90,
      efectoX: 3,
      efectoY: 3,
    },
  },
  {
    component: 'AssociationViz',
    title: 'Parcial',
    params: {
      modo: 'confusor',
      vista: 'residuos',
      nombres: { x: 'Estatura', y: 'Vocabulario', z: 'Edad' },
      niveles: ['6', '8', '10', '12'],
      n: 120,
      efectoX: 2.5,
      efectoY: 2.5,
    },
  },
  {
    component: 'AssociationViz',
    title: 'Espuria',
    params: { modo: 'espuria', nombres: { x: 'Serie A', y: 'Serie B' }, pasos: 150 },
  },
  {
    component: 'AssociationViz',
    title: 'Matriz',
    params: {
      modo: 'matriz',
      variables: [
        { nombre: 'Horas de sueño', valores: [7, 6, 8, 5, 7, 6, 9, 5] },
        { nombre: 'Café', valores: [1, 2, 0, 3, 1, 2, 0, 4] },
        { nombre: 'Calificación', valores: [8, 7, 9, 6, 8, 7, 9, 5] },
      ],
    },
  },
  {
    component: 'AssociationViz',
    title: 'Tabla de contingencia',
    params: {
      modo: 'contingencia',
      enfoque: 'cramer',
      filas: { nombre: 'Turno', categorias: ['Mañana', 'Tarde'] },
      columnas: { nombre: 'Resultado', categorias: ['Aprobada', 'Rechazada', 'Retrabajo'] },
      conteos: [
        [25, 15, 10],
        [10, 20, 20],
      ],
    },
  },
  {
    component: 'AssociationViz',
    title: 'MIC',
    params: {
      modo: 'mic',
      generador: { tipo: 'senoidal', n: 80, ruido: 0.15 },
      nombres: { x: 'Hora', y: 'Demanda' },
    },
  },
];
